image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-browser
  - port: 1-10000
    onOpen: ignore
  - port: 3000
    onOpen: notify

tasks:

  - name: Admin Helper
    command: gp ports await 8080 && sh .utils/info.sh

  - name: WP Server
    init: |
      # Install wp-cli dotenv package
      wp package install aaemnnosttv/wp-cli-dotenv-command:^2.0
      # Install vendor
      composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction

      # Create .env file
      wp dotenv init --template=.env.example --with-salts --force
      wp dotenv set WP_HOME $(gp url 8080)
      
      cd web/app/themes/theme
      composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
      yarn install
      yarn run build
      
      cd ../../../..
    command: wp dotenv set WP_HOME $(gp url 8080) && wp server --host=0.0.0.0 --port=8080